// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv99jfNKUQ65L7kU4-XZX6gfpqZJAnEjo',
    appId: '1:140125063858:web:10f82ada9b250896a8d7ab',
    messagingSenderId: '140125063858',
    projectId: 'gradeflow-b161d',
    authDomain: 'gradeflow-b161d.firebaseapp.com',
    storageBucket: 'gradeflow-b161d.firebasestorage.app',
    measurementId: 'G-CKB9QYBY80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm56ykg0LP6t3awvKQ8xjh4rec3dauelw',
    appId: '1:140125063858:android:a7b10a0bde6a2bf0a8d7ab',
    messagingSenderId: '140125063858',
    projectId: 'gradeflow-b161d',
    storageBucket: 'gradeflow-b161d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1EoTyaesnPHC5zcaHPeJDZntrWXQ_g4',
    appId: '1:140125063858:ios:5d6f5c1112e516e7a8d7ab',
    messagingSenderId: '140125063858',
    projectId: 'gradeflow-b161d',
    storageBucket: 'gradeflow-b161d.firebasestorage.app',
    iosClientId: '140125063858-87oik44fd5a270uo797sugc4d8n66el3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapaMaterias',
  );
}
